// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DueDateCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("calculation_method")]
        public string CalculationMethod { get; set; }

        [JsonProperty("last_period_date")]
        public DateTimeOffset LastPeriodDate { get; set; }

        [JsonProperty("estimated_conception_date")]
        public DateTimeOffset EstimatedConceptionDate { get; set; }

        [JsonProperty("due_date")]
        public DateTimeOffset DueDate { get; set; }

        [JsonProperty("current_progress")]
        public CurrentProgress CurrentProgress { get; set; }

        [JsonProperty("time_until_due")]
        public TimeUntilDue TimeUntilDue { get; set; }

        [JsonProperty("upcoming_milestones")]
        public object[] UpcomingMilestones { get; set; }

        [JsonProperty("important_dates")]
        public ImportantDates ImportantDates { get; set; }

        [JsonProperty("disclaimer")]
        public string Disclaimer { get; set; }
    }

    public partial class CurrentProgress
    {
        [JsonProperty("days_pregnant")]
        public long DaysPregnant { get; set; }

        [JsonProperty("weeks_pregnant")]
        public long WeeksPregnant { get; set; }

        [JsonProperty("days_into_week")]
        public long DaysIntoWeek { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }

        [JsonProperty("trimester")]
        public long Trimester { get; set; }

        [JsonProperty("percentage_complete")]
        public double PercentageComplete { get; set; }
    }

    public partial class ImportantDates
    {
        [JsonProperty("end_first_trimester")]
        public DateTimeOffset EndFirstTrimester { get; set; }

        [JsonProperty("end_second_trimester")]
        public DateTimeOffset EndSecondTrimester { get; set; }

        [JsonProperty("full_term_begins")]
        public DateTimeOffset FullTermBegins { get; set; }
    }

    public partial class TimeUntilDue
    {
        [JsonProperty("days")]
        public long Days { get; set; }

        [JsonProperty("weeks")]
        public long Weeks { get; set; }

        [JsonProperty("days_extra")]
        public long DaysExtra { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }

        [JsonProperty("is_overdue")]
        public bool IsOverdue { get; set; }
    }
}
